org: meng0052
app: express-api-app
service: express-api-app

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: '20201221'

functions:
  api:
    handler: handler.handler
    events:
      - http:
          path: /
          method: ANY
          cors:
              origin: '*'
      - http:
          path: /{proxy+}
          method: ANY
          cors:
              origin: '*'
    environment:
      TMDB_API_KEY: ${param:TMDB_API_KEY}
      TMDB_BASE_URL: https://api.themoviedb.org/3/

plugins:
  - serverless-offline
